apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: hello-istio-v1
  labels:
    demo: istio-external-services
spec:
  hosts:
    - hello-istio-v1.apps.coachella.cf-app.com
  location: MESH_EXTERNAL
  ports:
  - number: 8080
    name: http
    protocol: HTTP
    targetPort: 443
  - number: 443
    name: https
    protocol: HTTPS
    targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: hello-istio-v2
  labels:
    demo: istio-external-services
spec:
  hosts:
    - hello-istio-v2.apps.coachella.cf-app.com
  location: MESH_EXTERNAL
  ports:
  - number: 8081
    name: http
    protocol: HTTP
    targetPort: 443
  - number: 443
    name: https
    protocol: HTTPS
    targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: hello-istio-v1
  labels:
    demo: istio-external-services
spec:
  host: hello-istio-v1.apps.coachella.cf-app.com
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 8080
      tls:
        mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: hello-istio-v2
  labels:
    demo: istio-external-services
spec:
  host: hello-istio-v2.apps.coachella.cf-app.com
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 8081
      tls:
        mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: cf-service-v1
  labels:
    demo: istio-external-services
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: cf-service-v2
  labels:
    demo: istio-external-services
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 81
      name: http
      protocol: HTTP
    hosts:
      - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: egressgateway-for-cf-services
  labels:
    demo: istio-external-services
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hello-istio-v1
  labels:
    demo: istio-external-services
spec:
  hosts:
  - hello-istio-v1.apps.coachella.cf-app.com
  gateways:
  - mesh
  http:
  - match:
    - port: 80
    fault:
      abort:
        httpStatus: 418
        percentage:
          value: 20
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 80
      weight: 30
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 81
      weight: 70
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cf-service
  labels:
    demo: istio-external-services
spec:
  hosts:
  - "*"
  gateways:
  - cf-service-v1
  - cf-service-v2
  http:
  - match:
    - gateways:
      - cf-service-v1
    rewrite:
      authority: hello-istio-v1.apps.coachella.cf-app.com
    route:
    - destination:
        host: hello-istio-v1.apps.coachella.cf-app.com
        port:
          number: 8080
      weight: 100
  - match:
    - gateways:
      - cf-service-v2
    rewrite:
      authority: hello-istio-v2.apps.coachella.cf-app.com
    route:
    - destination:
        host: hello-istio-v2.apps.coachella.cf-app.com
        port:
          number: 8081
      weight: 100
